### ISSUE TITLE
JEI GUI Change For Additional Stats

### ISSUE THREAD

**Issue by EnderofGames** [Lance5057/Tinkers-Compendium#100]
![6](https://user-images.githubusercontent.com/17417666/54883646-7716f980-4e2d-11e9-935b-36acc348b920.PNG)

![7](https://user-images.githubusercontent.com/17417666/54883679-bcd3c200-4e2d-11e9-8429-2f46c35ee0a6.PNG)

Not 100% sure how to change how JEI represents tool stats on TCon, but when including Compendium it would be very nice to get one per page, so that it doesn't leak everywhere. 

Also, removing the extra modifier names that are not used would help splitting the sides of the gui, and I'm sure you're on top of that already.

**Comment by Royal-Jelly** [comment]
if your using a mod that adds TConstruct materials to JEI try removing that as its its incompatible with most Tinkers addons

**Comment by EnderofGames** [comment]
You are correct that Tinker's JEI is in the pack, I had thought it was a compatibility made with TCon itself, not a third mod. I will bring this request to them.
