### ISSUE TITLE
black and pink missing texture as well as some blocks not looking finished

### ISSUE THREAD

**Issue by volcanicmc** [Lance5057/Tinkers-Compendium#127]
i was looking at some of the blocks in jei and i can see a lot of pink and black missing texture blocks, as well as looking at some stuff that looks like it is semi finished and its very confusing. i just wanted to bring this up so that i might be able to get and answer as to if its cuz your still working on updating those parts or if i hit a bug that i cant get rid of. thank you for all your hard work on this mod and i hope it all comes together well in the end

**Comment by volcanicmc** [comment]
![Jre1 8 0_201 Screenshot 2019 07 27 - 18 11 20 01](https://user-images.githubusercontent.com/51584434/61999943-15e08a80-b09a-11e9-97b2-b6b91269cb0b.png)
![Jre1 8 0_201 Screenshot 2019 07 27 - 18 11 24 09](https://user-images.githubusercontent.com/51584434/61999944-16792100-b09a-11e9-8bfa-f285f0bede7d.png)
the pink and black textures i was talking about and the unfinished looking blocks are the finishing anvil and hammering table but im not sure if those are really unfinished or if those blocks are placeholder until you implement the full content

**Comment by alkyll** [comment]
Pretty sure these are WIP Blocks, Entities, or Items. Pink and black boxes are typically untextured items that are most likely unfinished.

**Comment by volcanicmc** [comment]
i imagine so it just kinda bothered me a bit since like the rose gold block can be made but it wont be a proper block afterwords and then it becomes a block that breaks in one hit by a fist in survival

**Comment by volcanicmc** [comment]
the other thing that bothered me was that some of the items that look finished dont seem to have a recipe for crafting them and i dont have an offical document or something telling me what is and isnt usable so it confuses me a bit
