### ISSUE TITLE
Tinkers' GUI in multiplayer is no longer localised per player.

### ISSUE THREAD

**Issue by joelou1** [Lance5057/Tinkers-Compendium#147]
Clicking an item in a Tinkers' Station/Forge or Armor Station(From both Construct's Armory and Compendium)/Forge in multiplayer while someone else is using it causes the UI to change for every players.

Step: 
1- Have Player One open a station.
2- Have Player One click a tool/weapon/armor.
3- Have Player Two open the same station.
4- Have Player Two click any other tool/weapon/armor.
5- Player One notices that his GUI changed.

**Comment by Lance5057** [comment]
This would be a Tinker's issue.
