### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by volcanicmc** [Lance5057/Tinkers-Compendium#151]
having a problem with opening my minecraft with this mod enabled, i have tried disabling it and everything loaded up so i think something is just conflicting with your mod and making it crash, Not to sure how to read this stuff myself but if you can identify anything in here and let me know what i need to do to fix it if its something on my end it would be much appreciated. thank you for taking your time to read this and i hope you are having or have had a nice day :)

https://paste.dimdev.org/etojazanub.sql

**Comment by XvBUSHvX** [comment]
Are you using TiC version "TConstruct-1.12.2-2.13.0.171.jar"?
They have a beta update that changes how they handle tool parts and there are a few mods that have to catch up with it. 

If you care to test it roll back your TiC to the previous (release) version and re-enable Tinker Complendium and it should work again. 

I actually stopped by to Inform Lance about the update their mod.

**Comment by volcanicmc** [comment]
so i went through and checked and i hadn't even had my TiC on the beta it was still on the last release patch so i thought lets see if the beta will let it work and the game loaded so i think that the beta one works for the newer version of TCompendium and it might have been the last release version of TiC that was conflicting and causing my crash on start up, now im only on the main menu as i wrote this so im not to sure about worlds yet but ill test it. but as i have figured out the problem somewhat thank you so much for mentioning that because it fixed it for me :)

**Comment by citrusMarmelade** [comment]
Issue should be closed as the latest beta Tcon <TConstruct-1.12.2-2.13.0.171.jar> is compatible with the latest beta build of this mod <tinkersdefense-1.4.2.30.jar> ?
