### ISSUE TITLE
[SUGGESTION] Rework Mod Vision

### ISSUE THREAD

**Issue by Xarmat-GitHub** [Lance5057/Tinkers-Compendium#188]
_All what I want to say in one sentence: "Focus on shields and nice shield mechanics and drop all the other content."_

### Take a step back and think about it
Tinkers Compendium has so much potential to be one of the "Must Have" adventure mods out there.
But I am not sure if its good to make this mod so full of features and content that no one see through it.
When I research all the tinkers mod out there, then I come back to Tinkers Compendium because of the shields.

**Mods out there that are valid**
- Tinkers Construct: No Explanation needed
- Construct's Armory: This mod concentrate on armor
- Tinkers Compendium: This mod focused on armor and shields

**Statistics / Downloads**
- Tinkers Construct **72 million**
- Construct's Armory: **13 million -> every 6 clients tested/use it with tinkers**
- Tinkers Compendium: **1,4 million -> only every 51 clients tested/use it with tinkers**

What I see here is that Tinkers Compendium is way to low on downloads and the potential to be one of the "Must Haves" can not be reached, but why?

### Main Problem (as far I see)
**Feature Creep: It adds way to much into the game:**
- Decorative Block, Bars, Trapdoors, Stake, Metal Doors
-- Many mods adds nice balanced and good looking Objects to the game - there is low need to use them from TComp
- Shears
-- There are a lot of mods that add shears, also the "need" of high tier shears in the modding community is quite low, no one can use them well in there modpacks
- Saw
-- Other mods adds them too, and there is low need to have higher tiered once
- Mallet
-- Many Tech Modpacks need them, but there are many mods who adds them, they have also enough tiers for any modpack maker
- Backpack
-- There are a lot of mods and they all are well known and works fine, many player would prefer them before learning something new
- Fishing Rod
-- There are mods that adds Rods and mechanics to have a reason to use them
- Fire Drill
-- For Modpacks, there are early game options until the player reach the flint and steel item, so low use for this
- Cloth Armor
-- Thaumcraft and co. brings there own cloth that are well balanced, there is low need for this
- Armor
-- Construct's Armory, makes a good job on there mod and it is not to complex to get into it. Its an easy mod to start with and follow. I would say that TComp has a hard time to get this position back and will not reach in the future

_All this content is / can be nice on its own, but when I have to add this to my modpack, **I will think twice if its worth.**_
_Often I drop this mod and take "Spartan Shields" and am frustrated of the standard way to craft them without using tinkers._

### Feature Focus (My personal thoughts)
- Shields
-- That is a part of TComp that has a high potential. Tinkers adds Tools & Weapons, Construct Armory -> Armor, but there is no tinkers Addon that adds shields
- Shield Mechanic
-- Vanilla Shields alone are boring; Adding some new Shield Mechanics would enhance the gameplay, example:
+ Buckler: Blocking Movement-Speed 100% | Block 25% Arrow Damage | Block 50% Melee Damage | Dash an enemy - 100% Debuff on them
+ Heartshield : Blocking Movement-Speed 50% | Block 75% Arrow Damage | Block 75% Melee Damage
+ Towershield: Overall Movement-Speed -25% (while Blocking -80%) | Block 100% Arrow Damage | Block 100% Melee Damage | Reduce DMG taken by 50% while worn
+ All this mechanics can be different, has other values, effects/potion effects based on the materials

**Comment**
Its just an input to think about. I would love to see well working and fun generating shield design in Tinkers.

**Comment by NightOps007** [comment]
I agree with Xarmat's POV. Other things already have good mods supporting them. The shields was the only reason I tried this in the first place. Then I got my inventory clogged up with useless armor drops from mobs and rage-quit, deleted the mod from my pack and came to give my opinion as well. Already found out that there is a config for mobs equipping armor(though someone else has apparently posted that the config doesn't work).
  Love the idea for baubles though and hope that you will continue development in that direction. Though you may want to create an independent mod for them. Something like Tinkers' Accessories...

**Comment by Lance5057** [comment]
Just because another mod does something doesn't mean anyone else should.
The reason I changed to Tinkers Compendium from Tinkers Defense is so I could expand as I got bored with "just shields".
Eventually everything will come together nicer, I just need the motivation to finish it, which things like this do not exactly help with.

**Comment by Xarmat-GitHub** [comment]
Then I am sorry for the potential de-motivation. This was not my intention. 

I just saw the potential of this mod and wondered why it's download's are low like this. 

I am aware of the hard work and the time spend on it, without any / much paying. 

I wish you good luck and burning motivation to bring it to a full release.
