### ISSUE TITLE
Stoned modifier stacks indefinitely with each MC restart

### ISSUE THREAD

**Issue by transcengopher** [Lance5057/Tinkers-Compendium#76]
When player wears armor with Stoned modifier, each time he logs in into the world after restarting Minecraft, another level of "td_stoned" modifier is stacked into player's walk speed attribute.

Reproduced on:
- Minecraft 1.12.2
- Forge 14.23.5.2770
- Mods:
  - Baubles 1.12 - 1.5.2
  - Tinkers' Construct 1.12 - 2.10.1.87
  - Tinkers' Compendium 1.4.2.18a

Steps:

1. Create new world (allow cheats)
2. Build a Chestplate so it has a "Stoned" tag
3. Put it on
4. Log out, restart Minecraft
5. Log in again
6. GOTO 4 (repeat couple of times)

Result:
![default](https://user-images.githubusercontent.com/23135845/46921436-3b6d3d80-d00c-11e8-9e15-30f4c3a29c20.png)

**Comment by transcengopher** [comment]
Looking at modifiers' code, I suspect this happens most other modifiers as well - due to no guarantees that `randomUUID()` is consistent across different runs.
Removing the armor piece doesn't seem to remove the modifier either.

**Comment by Lance5057** [comment]
This should be fixed in the latest update.
