### ISSUE TITLE
[MC-1.12.2] [Forge 2768] [TinCom/TinDef 1.4.2.19.2a] Crash on Startup

### ISSUE THREAD

**Issue by Excaliburning** [Lance5057/Tinkers-Compendium#80]
Hi !

Since the crash log seems different than the one on #77 I decided to open another issue thread.
They're quite similar tho. I have a lot of mods listed because I'm crash testing a few things, however no other mod seem related to this crash according to the report.

For some reason it generated two crash logs so, see both of them below (quite similar but they got registered for two different events, namely mod loading and game initialization).
[First bug report.](https://gist.github.com/Excaliburning/95e95b3be5c15fbc409ba8be645cafee)
[Second one.](https://gist.github.com/Excaliburning/6693d83e69856d3c80e76568bf97eb4a)

Thanks for looking into it !

**Comment by Lance5057** [comment]
Nihilite has been removed as a material for now. Should fix this issue.
