### ISSUE TITLE
Fishing pole issues 1.4.2.19.2a

### ISSUE THREAD

**Issue by capt-slowpoke** [Lance5057/Tinkers-Compendium#81]
The fishing pole seems to be casting the floater and immediately retracting it as if the right mouse button is being constantly held down. A single click casts the floater and immediately pulls it back. Vanilla fishing poles aren't doing this, and the floater sits in the water as normal. 
Is there a fix for this? 

tinkersdefense-1.4.2.19.2a
MC 1.12.2

**Comment by Syndaryl** [comment]
I am still having this problem in 1.4.2.20.1

**Comment by Lance5057** [comment]
The fishing pole wasnt supposed to be released yet, I accidently left it unlocked when i released some updates....

**Comment by Syndaryl** [comment]
well, can't wait for it to be finished then :D
