### ISSUE TITLE
help i don't know what this is or what mod this is from my world border stops at 5,000 blocks 

### ISSUE THREAD

**Issue by coolingwalter** [Lance5057/Tinkers-Compendium#82]
i am playing  and i stop at 5,000 block world border and i don't know why it's doing it however i have a big computer and trying to find out what mod is causing this if you can help me out that would be great keep in mind  it is a long list

and sorry it doesn't crash so there is no code

![2018-11-21_12 42 07](https://user-images.githubusercontent.com/37277242/48868303-f916e900-ed8d-11e8-959f-42a2647c2abf.png)

**Comment by coolingwalter** [comment]
it would be nice just to have an idea

**Comment by coolingwalter** [comment]
or is it a limitation with my pc

**Comment by grandwigg** [comment]
This isn't the Best place for that kind of issue.

Create a backup of the world, then disable mods one at a time to discover the cause.  (That's if the logs done have the answer.  It's also possible that a world border was inadvertent set by a player using commands.

That said, this forum us for specific issues or conflicts that directly apply to the mod, Tinkers Compendium, in this case.  You may want to try Reddit or the Minecraft forums.

**Comment by Lance5057** [comment]
This isn't my mod.
