### ISSUE TITLE
Mob drops that have no texture and item name of "null"

### ISSUE THREAD

**Issue by schindlershadow** [Lance5057/Tinkers-Compendium#84]
The following are dropped by mobs and have no texture and an item name of "null":
tinkerscompendium:greenmintcane
tinkerscompendium:gingerbread
tinkerscompendium:redmintcane

https://i.imgur.com/ycgW4TQ.png

tinkersdefense-1.4.2.20.1

**Comment by Lance5057** [comment]
These have been removed for now.
