### ISSUE TITLE
Crash on startup after removing moar tinkers

### ISSUE THREAD

**Issue by mando222** [Lance5057/Tinkers-Compendium#87]
I replaced my current moar tinkers with Tinkers-Compendium.  When starting MC up it crashed with this log https://paste.dimdev.org/yadoqevewi.mccrash

The only thing that changed from last successful run was the switch.

**Comment by Crafter07** [comment]
I am getting the same crash, has something to do with platinum from another mod i think, i have been trying myself to fix it, but i have not been successful.

**Comment by Lance5057** [comment]
This should be fixed now.
