### ISSUE TITLE
Config file isn't working.

### ISSUE THREAD

**Issue by SleepySukima** [Lance5057/Tinkers-Compendium#90]
Was trying to disable the fishing rod because it won't cast, but it just won't work. This is after restarting the game, of course.
 
Upon further inspection, no config files appear to do anything. Tried disabling shields, zweihander, etc. Nothing seems to work.

Using latest version: tinkersdefense-1.4.2.21.jar

**Comment by Lance5057** [comment]
Fixed in .22!
