### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lance5057/Tinkers-Compendium#91]
https://gist.github.com/P3rf3ctXZer0/2f035df96e6ebf7c37db5734b3e6465e

**Comment by mdbakpo** [comment]
Same here, gonna roll back to the previous version for now.

https://pastebin.com/mBVtjZEB

**Comment by Lance5057** [comment]
Fixed, caused by issue with Metallurgy.
